// ============================================================
// Suraksha Setu — India Major Cities & Disaster-Prone Locations
// Autocomplete index targeted exclusively for Indian metropolitan hubs
// and high-vulnerability disaster corridors (Seismic Zone V, Flash Flood,
// Landslide, Cloudburst, Cyclone Surge, and Riverine Inundation zones)
// ============================================================

export interface IndiaLocation {
  id: string;
  name: string;
  state: string;
  type: 'METRO' | 'MAJOR_CITY' | 'DISASTER_PRONE';
  category: string; // e.g. 'Seismic Zone V', 'Landslide & Subsidence', 'Riverine Floodplain', 'Cyclone Surge'
  description: string;
  lat: number;
  lng: number;
  zoom: number;
}

export const INDIA_LOCATIONS: IndiaLocation[] = [
  // —— Tier 1 Metros & Major State Capitals ——
  {
    id: 'loc_delhi',
    name: 'New Delhi / NCR',
    state: 'Delhi',
    type: 'METRO',
    category: 'Yamuna Floodplain & Seismic Zone IV',
    description: 'National Capital Region, vulnerable to Yamuna river swelling and northern fault lines',
    lat: 28.6139,
    lng: 77.2090,
    zoom: 11,
  },
  {
    id: 'loc_mumbai',
    name: 'Mumbai',
    state: 'Maharashtra',
    type: 'METRO',
    category: 'Coastal Cloudburst & High-Tide Surge',
    description: 'Island city vulnerable to monsoon deluge, Mithi River overflow, and oceanic squalls',
    lat: 19.0760,
    lng: 72.8777,
    zoom: 11.5,
  },
  {
    id: 'loc_kolkata',
    name: 'Kolkata',
    state: 'West Bengal',
    type: 'METRO',
    category: 'Hooghly Estuary & Bay of Bengal Cyclones',
    description: 'Low-lying deltaic metropolitan corridor vulnerable to cyclone landfalls and tidal ingress',
    lat: 22.5726,
    lng: 88.3639,
    zoom: 11,
  },
  {
    id: 'loc_chennai',
    name: 'Chennai',
    state: 'Tamil Nadu',
    type: 'METRO',
    category: 'Coromandel Coastal Cyclones & Urban Waterlogging',
    description: 'Vulnerable to North-East monsoon depressions, Adyar/Cooum river backflow',
    lat: 13.0827,
    lng: 80.2707,
    zoom: 11,
  },
  {
    id: 'loc_bengaluru',
    name: 'Bengaluru',
    state: 'Karnataka',
    type: 'METRO',
    category: 'Lake Valley Waterlogging & Convective Storms',
    description: 'Plateau basin with interconnected lake overflow and intense squalls',
    lat: 12.9716,
    lng: 77.5946,
    zoom: 11,
  },
  {
    id: 'loc_hyderabad',
    name: 'Hyderabad',
    state: 'Telangana',
    type: 'METRO',
    category: 'Musi Basin & Cloudburst Inundation',
    description: 'Deccan plateau urban center susceptible to rapid flash runoff',
    lat: 17.3850,
    lng: 78.4867,
    zoom: 11,
  },
  {
    id: 'loc_ahmedabad',
    name: 'Ahmedabad',
    state: 'Gujarat',
    type: 'MAJOR_CITY',
    category: 'Sabarmati Basin & Heatwave Corridor',
    description: 'Commercial hub subject to extreme summer heatwaves and Sabarmati discharge',
    lat: 23.0225,
    lng: 72.5714,
    zoom: 11,
  },
  {
    id: 'loc_pune',
    name: 'Pune',
    state: 'Maharashtra',
    type: 'MAJOR_CITY',
    category: 'Mutha-Mula River Basin & Ghat Rainfall',
    description: 'Western Ghats rain-shadow basin vulnerable to catchment release floods',
    lat: 18.5204,
    lng: 73.8567,
    zoom: 11,
  },
  {
    id: 'loc_lucknow',
    name: 'Lucknow',
    state: 'Uttar Pradesh',
    type: 'MAJOR_CITY',
    category: 'Gomti River Basin & Gangetic Convective Belt',
    description: 'Awadh plain monitoring base, vulnerable to river swelling and severe thunderstorms',
    lat: 26.8467,
    lng: 80.9462,
    zoom: 11.5,
  },
  {
    id: 'loc_patna',
    name: 'Patna',
    state: 'Bihar',
    type: 'MAJOR_CITY',
    category: 'Ganga-Gandak-Sone Confluence Floodplain',
    description: 'Surrounded by four major river systems, historically vulnerable to severe urban flooding',
    lat: 25.5941,
    lng: 85.1376,
    zoom: 11,
  },
  {
    id: 'loc_guwahati',
    name: 'Guwahati',
    state: 'Assam',
    type: 'MAJOR_CITY',
    category: 'Brahmaputra Valley & Heavy Monsoon Floodplain',
    description: 'Northeast gateway severely vulnerable to Brahmaputra river swelling and slope failures',
    lat: 26.1445,
    lng: 91.7362,
    zoom: 11.5,
  },
  {
    id: 'loc_kochi',
    name: 'Kochi',
    state: 'Kerala',
    type: 'MAJOR_CITY',
    category: 'Vembanad Estuary & Coastal Flooding',
    description: 'Low-lying backwater gateway prone to monsoon deluge and tidal surges',
    lat: 9.9312,
    lng: 76.2673,
    zoom: 11.5,
  },
  {
    id: 'loc_jaipur',
    name: 'Jaipur',
    state: 'Rajasthan',
    type: 'MAJOR_CITY',
    category: 'Semi-Arid Heatwave & Flash Storms',
    description: 'Extreme diurnal temperatures and episodic high-intensity thunderstorms',
    lat: 26.9124,
    lng: 75.7873,
    zoom: 11,
  },
  {
    id: 'loc_bhopal',
    name: 'Bhopal',
    state: 'Madhya Pradesh',
    type: 'MAJOR_CITY',
    category: 'Central Plateau & Dam Discharge Catchment',
    description: 'Central India hydrological junction between Narmada and Betwa basins',
    lat: 23.2599,
    lng: 77.4126,
    zoom: 11,
  },
  {
    id: 'loc_bhubaneswar',
    name: 'Bhubaneswar / Cuttack',
    state: 'Odisha',
    type: 'MAJOR_CITY',
    category: 'Mahanadi Delta Cyclone Corridor',
    description: 'Twin city delta corridor susceptible to Bay of Bengal severe cyclonic storms',
    lat: 20.2961,
    lng: 85.8245,
    zoom: 11,
  },
  {
    id: 'loc_srinagar',
    name: 'Srinagar',
    state: 'Jammu & Kashmir',
    type: 'MAJOR_CITY',
    category: 'Jhelum Basin & High Seismic Zone V',
    description: 'Intermontane valley vulnerable to Jhelum river overflow, snowstorms, and active faults',
    lat: 34.0837,
    lng: 74.7973,
    zoom: 11,
  },

  // —— High-Vulnerability Disaster-Prone Areas across India ——
  {
    id: 'loc_joshimath',
    name: 'Joshimath (Jyotirmath)',
    state: 'Uttarakhand',
    type: 'DISASTER_PRONE',
    category: 'Landslide & Land Subsidence Zone',
    description: 'High Himalayan moraine slope undergoing tectonic subsidence and seismic vulnerability',
    lat: 30.5574,
    lng: 79.5668,
    zoom: 13,
  },
  {
    id: 'loc_wayanad',
    name: 'Wayanad (Meppadi / Chooralmala)',
    state: 'Kerala',
    type: 'DISASTER_PRONE',
    category: 'Severe Debris Flow & Landslide Corridor',
    description: 'Steep Western Ghats catchment vulnerable to extreme torrential rain and catastrophic debris slips',
    lat: 11.5540,
    lng: 76.1320,
    zoom: 12.5,
  },
  {
    id: 'loc_kedarnath',
    name: 'Kedarnath / Mandakini Valley',
    state: 'Uttarakhand',
    type: 'DISASTER_PRONE',
    category: 'Cloudburst & Glacial Outburst Flood',
    description: 'Steep glacial catchment prone to extreme orographic cloudbursts and flash floods (Rudraprayag)',
    lat: 30.7352,
    lng: 79.0669,
    zoom: 12.5,
  },
  {
    id: 'loc_majuli',
    name: 'Majuli Island',
    state: 'Assam',
    type: 'DISASTER_PRONE',
    category: 'Riverine Erosion & Chronic Inundation',
    description: 'World’s largest river island, facing severe bank erosion and annual Brahmaputra submergence',
    lat: 26.9530,
    lng: 94.2090,
    zoom: 11.5,
  },
  {
    id: 'loc_kosi_saharsa',
    name: 'Kosi Basin (Supaul / Saharsa)',
    state: 'Bihar',
    type: 'DISASTER_PRONE',
    category: 'Avulsion & Siltation Floodplain ("Sorrow of Bihar")',
    description: 'Unpredictable river shifting, embankment breaches, and catastrophic northern Bihar floods',
    lat: 26.1260,
    lng: 86.5980,
    zoom: 11.5,
  },
  {
    id: 'loc_sundarbans',
    name: 'Sundarbans (Kakdwip / Gosaba)',
    state: 'West Bengal',
    type: 'DISASTER_PRONE',
    category: 'Super Cyclone & Tidal Storm Surge',
    description: 'Tidal mangrove delta vulnerable to saltwater ingress, levee breaches, and cyclone surges',
    lat: 21.8740,
    lng: 88.1850,
    zoom: 11,
  },
  {
    id: 'loc_bhuj',
    name: 'Bhuj / Rann of Kutch',
    state: 'Gujarat',
    type: 'DISASTER_PRONE',
    category: 'High Seismic Zone V & Tectonic Faults',
    description: 'Intense intraplate earthquake fault lines (Allah Bund, Kutch Mainland Fault)',
    lat: 23.2420,
    lng: 69.6669,
    zoom: 11.5,
  },
  {
    id: 'loc_dharamsala',
    name: 'Dharamshala / Kangra Valley',
    state: 'Himachal Pradesh',
    type: 'DISASTER_PRONE',
    category: 'Seismic Zone V & High Orographic Cloudburst',
    description: 'Dhauladhar foothills prone to severe seismic activity and sudden mountain downpours',
    lat: 32.2190,
    lng: 76.3234,
    zoom: 12,
  },
  {
    id: 'loc_shimla_kullu',
    name: 'Kullu & Beas Valley Corridor',
    state: 'Himachal Pradesh',
    type: 'DISASTER_PRONE',
    category: 'Flash River Surges & Slope Collapse',
    description: 'Beas river corridor vulnerable to dam overflows, highway cut-offs, and slope collapses',
    lat: 31.9579,
    lng: 77.1095,
    zoom: 12,
  },
  {
    id: 'loc_kuttanad',
    name: 'Kuttanad (Alappuzha)',
    state: 'Kerala',
    type: 'DISASTER_PRONE',
    category: 'Below Sea-Level Submergence Bowl',
    description: 'Deltaic paddy bowl lying 1 to 2 meters below sea level, susceptible to severe waterlogging',
    lat: 9.3800,
    lng: 76.4500,
    zoom: 12,
  },
  {
    id: 'loc_munsiari',
    name: 'Munsiari / Pithoragarh',
    state: 'Uttarakhand',
    type: 'DISASTER_PRONE',
    category: 'High-Altitude Flash Floods & Landslides',
    description: 'Gori Ganga valley corridor vulnerable to cloudburst debris dams and isolated road blockages',
    lat: 30.0667,
    lng: 80.2333,
    zoom: 12.5,
  },
  {
    id: 'loc_lahaul_spiti',
    name: 'Lahaul & Spiti (Rohtang Pass)',
    state: 'Himachal Pradesh',
    type: 'DISASTER_PRONE',
    category: 'Avalanche & High-Altitude Glacial Isolation',
    description: 'Extreme snow precipitation, avalanche tracks, and isolated trans-Himalayan valleys',
    lat: 32.5534,
    lng: 77.0142,
    zoom: 11,
  },
  {
    id: 'loc_uttarkashi',
    name: 'Uttarkashi / Bhagirathi Valley',
    state: 'Uttarakhand',
    type: 'DISASTER_PRONE',
    category: 'Active Faulting & Glacial Lake Outbursts',
    description: 'Seismic Zone IV/V junction prone to rockfalls, landslide dams, and flash river surges',
    lat: 30.7268,
    lng: 78.4354,
    zoom: 12,
  },
  {
    id: 'loc_puri_kendrapara',
    name: 'Puri / Kendrapara Coast',
    state: 'Odisha',
    type: 'DISASTER_PRONE',
    category: 'Direct Cyclone Landfall & Storm Inundation',
    description: 'Frequent landfall zone for severe cyclonic storms originating in the southern Bay of Bengal',
    lat: 19.8135,
    lng: 85.8312,
    zoom: 11.5,
  },
  {
    id: 'loc_cuddalore',
    name: 'Cuddalore / Nagapattinam Coast',
    state: 'Tamil Nadu',
    type: 'DISASTER_PRONE',
    category: 'Tsunami & Cyclonic Depression Corridor',
    description: 'Low-gradient coastal plain with historical vulnerability to Indian Ocean tsunamis and cyclones',
    lat: 11.7480,
    lng: 79.7714,
    zoom: 11.5,
  },
  {
    id: 'loc_bundelkhand',
    name: 'Bundelkhand (Jhansi / Banda)',
    state: 'Uttar Pradesh & MP',
    type: 'DISASTER_PRONE',
    category: 'Severe Drought & Heatwave Stress Zone',
    description: 'Rocky basalt plateau facing acute groundwater depletion and 47°C+ summer heatwaves',
    lat: 25.4484,
    lng: 78.5685,
    zoom: 11,
  },
  {
    id: 'loc_barmer',
    name: 'Barmer / Thar Desert Border',
    state: 'Rajasthan',
    type: 'DISASTER_PRONE',
    category: 'Desert Flash Floods & Extreme Heatwaves',
    description: 'Arid desert basin with gypsum subsoil that causes massive unabsorbed flash flooding',
    lat: 25.7521,
    lng: 71.3967,
    zoom: 11,
  },
];

/**
 * Filter Indian locations by search query (name, state, category, description).
 */
export function searchIndiaLocations(query: string, limit: number = 8): IndiaLocation[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  return INDIA_LOCATIONS.filter((loc) => {
    return (
      loc.name.toLowerCase().includes(q) ||
      loc.state.toLowerCase().includes(q) ||
      loc.category.toLowerCase().includes(q) ||
      loc.description.toLowerCase().includes(q)
    );
  }).slice(0, limit);
}
